export const MOMO_PAYMENT_CREATE_REQUEST = "MOMO_PAYMENT_CREATE_REQUEST";
export const MOMO_PAYMENT_CREATE_SUCCESS = "MOMO_PAYMENT_CREATE_SUCCESS";
export const MOMO_PAYMENT_CREATE_FAIL = "MOMO_PAYMENT_CREATE_FAIL";

export const MOMO_PAYMENT_STATUS_REQUEST = "MOMO_PAYMENT_STATUS_REQUEST";
export const MOMO_PAYMENT_STATUS_SUCCESS = "MOMO_PAYMENT_STATUS_SUCCESS";
export const MOMO_PAYMENT_STATUS_FAIL = "MOMO_PAYMENT_STATUS_FAIL";

export const MOMO_PAYMENT_RESET = "MOMO_PAYMENT_RESET";
